# Enable colors
set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Prefix key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Status Line Position
set-option -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

### Run tpm ###
run '~/.tmux/plugins/tpm/tpm'
