# Enable colors
set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Prefix key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Status Line Position
set-option -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme vague
set -g status on
set -g status-interval 1
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=#cdcdcd,bg=#1c1c24"
set -g status-justify absolute-centre

set -g message-style "fg=#252530,bg=#aeaed1"

set -g status-left "#[fg=#252530,bg=#aeaed1]  #H #[fg=#cdcdcd,bg=#252530]  #S "

set -g status-right " #[fg=#cdcdcd,bg=#252530] 󰃭 %A %d %b #[fg=#252530,bg=#aeaed1] 󰥔 %I:%M:%S %p "

setw -g window-status-separator " "
setw -g window-status-format "#[fg=#252530,bg=#d7d7d7] #I #[fg=#cdcdcd,bg=#252530] #W "
setw -g window-status-current-format "#[fg=#252530,bg=#f3be7c] #I #[fg=#cdcdcd,bg=#252530] #W "

# Pop-Up: Session list (menu)
bind w display-popup -E -w 30% -h 50% ~/.config/tmux/script/tmux-menu.sh

# Pop-Up: LazyGit
bind g display-popup -d "#{pane_current_path}" -E -w 80% -h 80% -E lazygit

### Run tpm ###
run '~/.tmux/plugins/tpm/tpm'
